name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Change to your Node version

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Create artifact
        run: tar -czf build-artifact.tar.gz node_modules dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-artifact.tar.gz

  start_and_check:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Change to your Node version

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .

      - name: Extract artifact
        run: tar -xzf build-artifact.tar.gz

      - name: Start the server
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: npm run start &

      - name: Check server is running
        run: curl --max-time 10 --silent --fail http://localhost:3000